### ISSUE TITLE
Pitch bend range wrong

### ISSUE THREAD

**Issue by cesaref** [notthetup/midimessage#2]
I noticed that the pitch bend value is being incorrectly calculated - there's a bit shift by 8 instead of 7 for the msb (7 bit values in midi):

diff --git a/src/index.js b/src/index.js
index 171b9ef..00c03cf 100644
--- a/src/index.js
+++ b/src/index.js
@@ -90,7 +90,7 @@ export default function(event){
                                this.messageType = "pitchbendchange";
                                var msb = event.data[2] & 0x7F;
                                var lsb = event.data[1] & 0x7F;
-                               this.pitchBend = (msb << 8) + lsb;
+                               this.pitchBend = (msb << 7) + lsb;
                        break;
                }
        }

This will fix things, and will then match the spec

**Comment by notthetup** [comment]
Good catch!. I haven't really been maintaining this package, but will fix this and do a release asap. Possibly over the weekend.
